"""
Django settings for bot_middleware project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-@nqv=368eb7if_9+llcgw661@w*ei(gelj=ud^r4*0l5ph58('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SO_proxy',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bot_middleware.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bot_middleware.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

#Queries StackOverflow
AT_LEAST_ONE_TAG_AND_INTITLE_FILTER= "https://api.stackexchange.com//2.2/search?pagesize=100&order=desc&sort=activity&tagged=%(tags)s&intitle=%(intitle)s&site=stackoverflow&filter=!)5__yhuriMxCPxpOvE.1fkRjrfXv"
MULTIPLE_TAGS_FILTER = "https://api.stackexchange.com/2.2/questions?pagesize=100&order=desc&sort=votes&tagged=%(tags)s&site=stackoverflow&filter=!BLtFdlgN1z2OoCXlXTyTAvJuybpOSy"
SIMILAR_QUESTION_FILTER  = "https://api.stackexchange.com/2.2/similar?pagesize=100&order=desc&sort=relevance&tagged=%(tags)s&title=%(intitle)s&site=stackoverflow&filter=!)5cCAfQ89FJ*hTGUy)0qNg)rgS6L"

MINIMAL_NUMBER_OF_ENTITIES = 3
MINIMUM_INFORMATION_ACQUIRED = 0.75

TAGME_TAG_URI = "https://tagme.d4science.org/tagme/tag?lang=en&include_abstract=true&include_categories=true&gcube-token=71dc7ebc-edbc-40b5-82ec-ce4aa096004d-843339462&text=%(text)s"
TAGME_RELATEDNESS_URI = "https://tagme.d4science.org/tagme/rel?gcube-token=71dc7ebc-edbc-40b5-82ec-ce4aa096004d-843339462&%(ids)s"
