# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_match', models.IntegerField(blank=True, default=0)),
                ('term_overlap', models.FloatField(blank=True, default=0)),
                ('synonym_overlap', models.FloatField(blank=True, default=0)),
                ('language_model_score', models.FloatField(blank=True, default=0)),
                ('sentence_length', models.FloatField(blank=True, default=0)),
                ('sentence_location', models.FloatField(blank=True, default=0)),
                ('esa', models.FloatField(blank=True, default=0)),
                ('word_embedding', models.FloatField(blank=True, default=0)),
                ('entity_linking', models.FloatField(blank=True, default=0)),
                ('has_code', models.IntegerField(blank=True, default=0)),
                ('label', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
