# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-13 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SO_proxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdata',
            old_name='entity_linking',
            new_name='answer_length',
        ),
        migrations.RenameField(
            model_name='trainingdata',
            old_name='esa',
            new_name='semantic_score',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='language_model_score',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='sentence_length',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='sentence_location',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='synonym_overlap',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='word_embedding',
        ),
    ]
