# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SO_proxy', '0004_auto_20180218_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdata',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
